// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7jy47ZFMeCM_FhhRw8OcdTJtcUrxRdI',
    appId: '1:940538294533:web:ea5edccbe0afa21356876c',
    messagingSenderId: '940538294533',
    projectId: 'smarthome-a95a9',
    authDomain: 'smarthome-a95a9.firebaseapp.com',
    storageBucket: 'smarthome-a95a9.firebasestorage.app',
    measurementId: 'G-27BBSBDNZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3h9Nqbz9neEnzbva6XKXYss71cCHUkU',
    appId: '1:940538294533:android:5d4dbdc67a26f06456876c',
    messagingSenderId: '940538294533',
    projectId: 'smarthome-a95a9',
    storageBucket: 'smarthome-a95a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP18jaTyN0Ds6IahJRd9HKQcyoKZRX7AQ',
    appId: '1:940538294533:ios:cc769fca2d628fb556876c',
    messagingSenderId: '940538294533',
    projectId: 'smarthome-a95a9',
    storageBucket: 'smarthome-a95a9.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP18jaTyN0Ds6IahJRd9HKQcyoKZRX7AQ',
    appId: '1:940538294533:ios:cc769fca2d628fb556876c',
    messagingSenderId: '940538294533',
    projectId: 'smarthome-a95a9',
    storageBucket: 'smarthome-a95a9.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs7jy47ZFMeCM_FhhRw8OcdTJtcUrxRdI',
    appId: '1:940538294533:web:ba95a1b525a9d37c56876c',
    messagingSenderId: '940538294533',
    projectId: 'smarthome-a95a9',
    authDomain: 'smarthome-a95a9.firebaseapp.com',
    storageBucket: 'smarthome-a95a9.firebasestorage.app',
    measurementId: 'G-KKCJ0TFQLH',
  );
}
